version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    container_name: handmade_store_app
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - EMAIL_SENDER_LOGIN=${EMAIL_SENDER_LOGIN}
    ports:
      - '8080:8080'



  db:
    image: 'postgres:latest'
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'