spring:
  application:
    name: handmade-store
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
api:
  backend-base-url: http://localhost:8080
  frontend-base-url: http://localhost:5173
  base-resource-path: /api/v1
jwt:
  expiration: 1h
  refresh-expiration: 30d
  secret: ${JWT_SECRET}
email:
  sender:
    login: ${EMAIL_SENDER_LOGIN}
  confirmation:
    token:
      lifetime: 15m
reset:
  password:
    token:
      lifetime: 15m